#!/usr/bin/env python3
"""Generate tool-specific agent instructions from the shared source tree.

The generator intentionally uses only the Python standard library so it works on
Python 3.9 and newer.  `--check` is read-only and reports missing, stale, and
unexpected files in the generated tool directories.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, Iterable, Mapping, NamedTuple


SCRIPT_ROOT = Path(__file__).resolve().parents[1]
COMMON_RULES_PATH = "~/.agents/my-agents/rules/common/*.md"
TYPESCRIPT_RULES_PATH = "~/.agents/my-agents/rules/typescript/*.md"
GENERATED_MARKDOWN_HEADER = "<!-- Generated by scripts/generate.py; do not edit. -->\n\n"
GENERATED_TOML_HEADER = "# Generated by scripts/generate.py; do not edit.\n"


class Role(NamedTuple):
    description: str
    body: str


def read_source(path: Path) -> str:
    """Read UTF-8 text and normalize its final newline."""
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def load_json(path: Path) -> Mapping[str, object]:
    with path.open(encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError("%s must contain a JSON object" % path)
    return value


def parse_role(path: Path) -> Role:
    """Parse the deliberately small frontmatter format used by shared roles."""
    source = read_source(path)
    if not source.startswith("---\n"):
        raise ValueError("%s must start with role frontmatter" % path)
    closing = source.find("\n---\n", 4)
    if closing == -1:
        raise ValueError("%s has unterminated role frontmatter" % path)
    metadata = source[4:closing]
    body = source[closing + len("\n---\n") :]
    description = None
    for line in metadata.splitlines():
        key, separator, value = line.partition(":")
        if key.strip() == "description" and separator:
            description = value.strip()
            break
    if not description:
        raise ValueError("%s must define a role description" % path)
    body = body.lstrip("\n")
    if not body.strip():
        raise ValueError("%s must define a role body" % path)
    return Role(description=description, body=body)


def load_shared(root: Path) -> tuple[str, Dict[str, str], Dict[str, Role]]:
    instructions_path = root / "shared" / "instructions.md"
    if not instructions_path.is_file():
        raise FileNotFoundError("Missing shared instructions: %s" % instructions_path)

    instructions = read_source(instructions_path)
    rules_dir = root / "shared" / "rules" / "common"
    rule_paths = sorted(rules_dir.glob("*.md"))
    if not rule_paths:
        raise FileNotFoundError("No common rules found in %s" % rules_dir)
    rules = {path.stem: read_source(path) for path in rule_paths}

    roles_dir = root / "shared" / "roles"
    role_paths = sorted(roles_dir.glob("*.md"))
    if not role_paths:
        raise FileNotFoundError("No shared roles found in %s" % roles_dir)
    roles = {path.stem: parse_role(path) for path in role_paths}
    return instructions, rules, roles


def common_rules_body(rules: Mapping[str, str]) -> str:
    sections = []
    for name in sorted(rules):
        sections.append("### %s\n\n%s" % (name.replace("-", " ").title(), rules[name].rstrip()))
    return "\n\n".join(sections)


def role_guidance(tool: str, adapter_instructions: str, role_body: str) -> str:
    global_path = "~/.claude/CLAUDE.md" if tool == "claude" else "~/.codex/AGENTS.md"
    return (
        "%s\n\n"
        "## Shared guidance\n\n"
        "Before acting, read `%s`, which contains the shared global instructions. "
        "Then read the applicable common guidance in `%s`. "
        "For TypeScript or JavaScript work, also read every applicable file in `%s`.\n\n"
        "%s\n"
        % (
            role_body.rstrip(),
            global_path,
            COMMON_RULES_PATH,
            TYPESCRIPT_RULES_PATH,
            adapter_instructions.rstrip(),
        )
    )


def routing_table(adapter: Mapping[str, object], include_effort: bool) -> str:
    roles = adapter["roles"]
    if not isinstance(roles, dict):
        raise ValueError("adapter roles must be an object")
    header = "| Role | Model |"
    divider = "| --- | --- |"
    if include_effort:
        header += " Reasoning effort |"
        divider += " --- |"
    rows = [header, divider]
    for name in sorted(roles):
        config = roles[name]
        if not isinstance(config, dict):
            raise ValueError("role config for %s must be an object" % name)
        row = "| `%s` | `%s` |" % (name, config["model"])
        if include_effort:
            row += " `%s` |" % config["model_reasoning_effort"]
        rows.append(row)
    return "\n".join(rows)


def global_document(
    tool: str,
    instructions: str,
    rules: Mapping[str, str],
    adapter: Mapping[str, object],
) -> str:
    effort = tool == "codex"
    return (
        GENERATED_MARKDOWN_HEADER
        +
        "# Global guidance\n\n"
        "%s\n\n"
        "## %s guidance\n\n%s\n\n"
        "## Common rules\n\n%s\n\n"
        "## TypeScript and JavaScript\n\n"
        "For TypeScript or JavaScript tasks, read every applicable file in `%s` before changing code.\n\n"
        "## Agent routing\n\n%s\n"
        % (
            instructions.rstrip(),
            tool.title(),
            adapter["global_instructions"],
            common_rules_body(rules),
            TYPESCRIPT_RULES_PATH,
            routing_table(adapter, include_effort=effort),
        )
    )


def claude_agent(
    name: str, config: Mapping[str, object], role: Role, adapter_instructions: str
) -> str:
    tools = config["tools"]
    if not isinstance(tools, list) or not all(isinstance(value, str) for value in tools):
        raise ValueError("Claude tools for %s must be a list of strings" % name)
    frontmatter = (
        "---\n"
        "name: %s\n"
        "description: %s\n"
        "tools: %s\n"
        "model: %s\n"
        "---\n\n"
        % (name, json.dumps(role.description, ensure_ascii=False), ", ".join(tools), config["model"])
    )
    return frontmatter + GENERATED_MARKDOWN_HEADER + role_guidance("claude", adapter_instructions, role.body)


def codex_agent(name: str, config: Mapping[str, object], role: Role, adapter_instructions: str) -> str:
    required = ("model", "model_reasoning_effort", "sandbox_mode")
    missing = [key for key in required if key not in config]
    if missing:
        raise ValueError("Codex role %s missing %s" % (name, ", ".join(missing)))
    guidance = role_guidance("codex", adapter_instructions, role.body)
    # JSON basic-string escaping is valid TOML basic-string escaping and safely
    # preserves quotes, backslashes, and line breaks in generated instructions.
    return (
        GENERATED_TOML_HEADER
        +
        "name = %s\n"
        "description = %s\n"
        "model = %s\n"
        "model_reasoning_effort = %s\n"
        "sandbox_mode = %s\n"
        "developer_instructions = %s\n"
        % (
            json.dumps(str(name), ensure_ascii=False),
            json.dumps(role.description, ensure_ascii=False),
            json.dumps(str(config["model"]), ensure_ascii=False),
            json.dumps(str(config["model_reasoning_effort"]), ensure_ascii=False),
            json.dumps(str(config["sandbox_mode"]), ensure_ascii=False),
            json.dumps(guidance, ensure_ascii=False),
        )
    )


def expected_files(root: Path) -> Dict[Path, str]:
    instructions, rules, roles = load_shared(root)
    claude = load_json(root / "adapters" / "claude.json")
    codex = load_json(root / "adapters" / "codex.json")
    claude_roles = claude.get("roles")
    codex_roles = codex.get("roles")
    if not isinstance(claude_roles, dict) or not isinstance(codex_roles, dict):
        raise ValueError("Both adapters must contain a roles object")
    if set(roles) != set(claude_roles) or set(roles) != set(codex_roles):
        raise ValueError("shared roles and adapter role keys must match")

    generated = root / "generated"
    expected: Dict[Path, str] = {
        generated / "claude" / "CLAUDE.md": global_document("claude", instructions, rules, claude),
        generated / "codex" / "AGENTS.md": global_document("codex", instructions, rules, codex),
    }
    for name in sorted(roles):
        claude_config = claude_roles[name]
        codex_config = codex_roles[name]
        if not isinstance(claude_config, dict) or not isinstance(codex_config, dict):
            raise ValueError("adapter role definitions must be objects")
        expected[generated / "claude" / "agents" / (name + ".md")] = claude_agent(
            name, claude_config, roles[name], str(claude["agent_instructions"])
        )
        expected[generated / "codex" / "agents" / (name + ".toml")] = codex_agent(
            name, codex_config, roles[name], str(codex["agent_instructions"])
        )
    return expected


def unexpected_generated_files(root: Path, expected: Mapping[Path, str]) -> Iterable[Path]:
    generated = root / "generated"
    if not generated.exists():
        return []
    expected_paths = set(expected)
    return sorted(
        path
        for path in generated.rglob("*")
        if (path.is_file() or path.is_symlink()) and path not in expected_paths
    )


def unsafe_output_paths(root: Path, expected: Mapping[Path, str]) -> list[str]:
    """Return unsafe generated paths without following a possible symlink.

    A generator must make this check before writing any output.  In particular,
    an existing `generated`, tool directory, or output-file symlink could point
    outside the repository and otherwise turn an ordinary regeneration into an
    overwrite of a user's settings.
    """
    output_paths = set(expected)
    inspected = set()
    for output in output_paths:
        try:
            relative = output.relative_to(root)
        except ValueError:
            return ["output is outside the repository: %s" % output]
        current = root
        for component in relative.parts:
            current = current / component
            inspected.add(current)

    issues = []
    for path in sorted(inspected):
        relative = path.relative_to(root)
        if path.is_symlink():
            issues.append("%s is a symbolic link" % relative)
        elif path in output_paths:
            if path.exists() and not path.is_file():
                issues.append("%s exists but is not a regular file" % relative)
        elif path.exists() and not path.is_dir():
            issues.append("%s is an output ancestor but is not a directory" % relative)
    return issues


def check(root: Path, expected: Mapping[Path, str]) -> int:
    problems = []
    for path in sorted(expected):
        if not path.exists():
            problems.append("MISSING %s" % path.relative_to(root))
        elif path.read_text(encoding="utf-8") != expected[path]:
            problems.append("STALE %s" % path.relative_to(root))
    for path in unexpected_generated_files(root, expected):
        problems.append("UNEXPECTED %s" % path.relative_to(root))
    if problems:
        print("Generated files are out of date:", file=sys.stderr)
        print("\n".join(problems), file=sys.stderr)
        return 1
    print("Generated files are up to date.")
    return 0


def write_generated(expected: Mapping[Path, str]) -> None:
    for path in sorted(expected):
        content = expected[path]
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print("WROTE %s" % path)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report generated output drift without writing")
    parser.add_argument("--root", type=Path, default=SCRIPT_ROOT, help="repository root (default: script parent)")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    root = args.root.resolve()
    try:
        expected = expected_files(root)
    except (FileNotFoundError, ValueError, KeyError, json.JSONDecodeError) as error:
        print("Generation failed: %s" % error, file=sys.stderr)
        return 2
    unsafe_paths = unsafe_output_paths(root, expected)
    if unsafe_paths:
        print("Generation failed: unsafe generated output path(s):", file=sys.stderr)
        for path in unsafe_paths:
            print("- %s" % path, file=sys.stderr)
        return 2
    if args.check:
        return check(root, expected)
    write_generated(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
